### ISSUE TITLE
Some of the puzzles I encountered:

### ISSUE THREAD

**Issue by TaoRone** [anyproto/any-sync-node#99]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

I really like your project.
But I encountered some issues during deployment:

1. When I use the any sync network tool to generate a network, the mongo connect in the Consensus node will default to empty “connect:“” ”

2. When I use the any sync network tool to generate a network, the s3 settings in file_1.yml will default to missing the indexBucket

3. The Redis used must have the Reblom plugin installed, but many service providers do not provide it. It is only after seeing an error that one realizes it

4. When I use the any sync network tool to generate a network, if I use 127.0.0.1 for all addresses, I can see that the internal network is interconnected when running simultaneously. However, at this time, I modify 127.0.0.1 in the client's heart to an IPv4 address through IP: port and cannot successfully connect.

5. Meanwhile, if I directly set the address to IPV4 when using the any sync network tool to generate a network, this error message will appear: FATAL main can't start app {"error": "can't run service 'net. transport. yamux': listen TCP 203. xxx. xxx. 226:12583: bind: cannot assign requested address"}

(The environment I am using is a NAT machine, with only 10 IPV4 ports available for use)

6. I found that it doesn't seem to support pure IPv4 environments?

### Expected Behavior

RT

### Steps To Reproduce

I compiled on another machine with the same architecture and then placed the compiled bin file in my testing environment for testing
Encountered the above issues

### Environment

```markdown
- OS:Debian GNU/Linux
- Version: 12
```

**Comment by fb929** [comment]
For self-deployment, you can use the following tools:

1. https://github.com/anyproto/any-sync-dockercompose
2. https://forge.puppetlabs.com/modules/anyproto/anysync/readme or https://github.com/anyproto/puppet-anysync (it's same)
3. https://github.com/anyproto/ansible-anysync/

I recommend the first option, it requires the least amount of effort.
